INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N7255N','Rotary Wing',1,130,15000,143000,false,3400,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N6506R','Fixed Wing',1,174,18000,57000,false,56000,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N7255N','Rotary Wing',1,130,15000,3400,false,3400,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N6506R','Fixed Wing',1,174,18000,56000,false,56000,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N7166P','UAV',2,260,26000,802,false,802,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N3707R','Rotary Wing',2,150,20000,76621,false,76621,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N8877N','Rotary Wing',3,130,15000,47558,false,47558,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N4900P','Fixed Wing',3,270,31000,60783,false,60783,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N1010N','Fixed Wing',4,174,18000,14825,false,14825,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N2233R','Fixed Wing',4,270,31000,76483,false,76483,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N4576P','Fixed Wing',5,270,31000,11482,false,11482,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N4398N','Rotary Wing',5,130,15000,67004,false,67004,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N0987P','Rotary Wing',6,130,15000,66015,false,66015,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N0789R','Rotary Wing',6,130,15000,13396,false,13396,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N6671P','UAV',7,260,26000,45621,false,45621,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N6681P','Rotary Wing',7,150,20000,27226,false,27226,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N7781R','Rotary Wing',8,130,15000,30882,false,30882,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N8778R','Rotary Wing',8,130,15000,27460,false,27460,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N0980N','Fixed Wing',9,270,31000,85011,true,85011,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N0190N','Fixed Wing',9,174,18000,41595,false,41595,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N8801R','Fixed Wing',10,270,31000,7970,false,7970,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N8903R','Rotary Wing',10,150,20000,26626,false,26626,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N4867N','Rotary Wing',12,130,15000,66574,false,66574,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N4890N','Rotary Wing',12,150,20000,57092,true,57092,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N3402N','Rotary Wing',13,130,15000,36019,false,36019,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N4509P','UAV',13,260,26000,55067,false,55067,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N3980R','Rotary Wing',14,130,15000,20460,false,20460,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N3911R','Rotary Wing',14,150,20000,35623,false,35623,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N2497N','Fixed Wing',15,270,31000,71015,false,71015,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N2587N','Fixed Wing',15,174,18000,30380,false,30380,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N0989R','Fixed Wing',16,270,31000,67776,true,67776,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N0667P','Rotary Wing',16,130,15000,7302,false,7302,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N0898N','Rotary Wing',17,150,20000,70630,false,70630,NULL);
INSERT INTO APP.AIRCRAFT (TAIL_NUMBER,AIRCRAFT_TYPE,STATION_ID,MAX_SPEED,MAX_ALTITUDE,TOTAL_FILGHT_HOURS,MAINTENANCE_FLAG,CURRENT_MAINTENANCE_HOURS,END_OF_SERVICE_DATE) VALUES (
'N2121N','Fixed Wing',17,130,15000,14535,false,14535,NULL);
