/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author jgrimard
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aircraftView = new view.AircraftView();
        operationsView = new view.OperationsView();
        maintenanceView = new view.MaintenanceView();

        setLayout(new java.awt.CardLayout());
        add(aircraftView, "aircraftView");
        add(operationsView, "operationsView");
        operationsView.getAccessibleContext().setAccessibleName("");

        add(maintenanceView, "maintenanceView");
        maintenanceView.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.AircraftView aircraftView;
    private view.MaintenanceView maintenanceView;
    private view.OperationsView operationsView;
    // End of variables declaration//GEN-END:variables
}
