/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temporary;

import view.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jgrimard
 */
public class StationsViewTemp extends javax.swing.JPanel {

    /**
     * Creates new form StationsView
     */
    public StationsViewTemp() {
        getStationsTable();
        initComponents();
    }

    private final DefaultTableModel tableModel = new DefaultTableModel() {
        
        //Make table cells non-editable
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    //Fill table with results from Stations table in database
    private void getStationsTable() {
        final String CONNECTION = "jdbc:derby:FlightHours;create=true";
        try (Connection conn = DriverManager.getConnection(CONNECTION);
                Statement statement = conn.createStatement()) {
            ResultSet results = statement.executeQuery("SELECT * FROM STATIONS");
            ResultSetMetaData metaData = results.getMetaData();
            
            //Create column names
            Vector<String> columnNames = new Vector<String>();
            columnNames.add("Station Name");
            columnNames.add("Station Type");

            //Fill all rows with results
            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
            while (results.next()) {
                Vector<Object> vector = new Vector<Object>();
                vector.add(results.getObject(2));
                vector.add(results.getObject(3));
                data.add(vector);
            }

            tableModel.setDataVector(data, columnNames);

        } catch (SQLException sqlExcept) {
            sqlExcept.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        stationsTable = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        stationsTable.setModel(tableModel);
        jScrollPane1.setViewportView(stationsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 352;
        gridBagConstraints.ipady = 134;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stationsTable;
    // End of variables declaration//GEN-END:variables
}
